// RadarX Phase 1 — Read-only crypto intelligence engine.
// No trading, withdrawal, user-data, or execution endpoints are included.

export const CONFIG = Object.freeze({
  timeframes:{regime:'4h',setup:'1h',trigger:'15m',fast:'5m'},
  trend:{emaFast:20,emaMid:50,emaSlow:200,adxPeriod:14,minAdx:20,pullbackAtrMax:1.5,breakoutBufferAtr:.10,stopAtr:1.5,stopBufferAtr:.10,minNetRR:1.5},
  breakout:{lookback:20,breakoutBufferAtr:.10,minRvol:1.5,minVolumeAcceleration:1.15,maxSpreadBps:20,minObiLong:.10,minObiShort:-.10,depthBandPct:.005,minLiquidityQuality:60,wickReject:.60},
  meanReversion:{rsiPeriod:14,oversold:30,overbought:70,bbPeriod:20,bbStdDev:2,trendEma:200,atrPeriod:14,stopAtr:1.5,swingBufferAtr:.25,panicRvol:3,panicBodyFraction:.65},
  liquidity:{maxSpreadBps:20,minQuality:60,minTrades24h:100,minQuoteVolume24h:null,depthBandPct:.005},
  costs:{feeRate:null,slippageBps:null},dedup:{cooldownMs:900000}
});
const num=x=>Number.isFinite(Number(x));
const clamp=(x,lo=0,hi=100)=>Math.max(lo,Math.min(hi,Number(x)));
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
const norm=(x,lo,hi)=>x==null||!Number.isFinite(x)?null:clamp((x-lo)/(hi-lo)*100);

export function sma(a,n){const o=Array(a.length).fill(null);for(let i=n-1;i<a.length;i++)o[i]=mean(a.slice(i-n+1,i+1));return o}
export function ema(a,n){const o=Array(a.length).fill(null);if(a.length<n)return o;let p=mean(a.slice(0,n));o[n-1]=p;const k=2/(n+1);for(let i=n;i<a.length;i++)o[i]=p=k*a[i]+(1-k)*p;return o}
export function rma(a,n){const o=Array(a.length).fill(null);if(a.length<n)return o;let p=mean(a.slice(0,n));o[n-1]=p;for(let i=n;i<a.length;i++)o[i]=p=((n-1)*p+a[i])/n;return o}
export function trueRange(c){return c.map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close)):x.high-x.low)}
export function atr(c,n=14){return rma(trueRange(c),n)}
export function rsi(a,n=14){const g=[],l=[],o=Array(a.length).fill(null);for(let i=1;i<a.length;i++){const d=a[i]-a[i-1];g.push(Math.max(d,0));l.push(Math.max(-d,0))}const G=rma(g,n),L=rma(l,n);for(let i=n;i<a.length;i++)o[i]=L[i-1]===0?100:100-100/(1+G[i-1]/L[i-1]);return o}
export function bollinger(a,n=20,k=2){const m=sma(a,n),u=Array(a.length).fill(null),l=Array(a.length).fill(null);for(let i=n-1;i<a.length;i++){const x=a.slice(i-n+1,i+1),mu=m[i],sd=Math.sqrt(mean(x.map(v=>(v-mu)**2)));u[i]=mu+k*sd;l[i]=mu-k*sd}return{middle:m,upper:u,lower:l}}
export function macd(a,fast=12,slow=26,signal=9){const f=ema(a,fast),s=ema(a,slow),line=a.map((_,i)=>f[i]!=null&&s[i]!=null?f[i]-s[i]:null),v=line.filter(num),sv=ema(v,signal),sig=Array(line.length).fill(null);let j=0;for(let i=0;i<line.length;i++)if(line[i]!=null)sig[i]=sv[j++];return{line,signal:sig,histogram:line.map((v,i)=>v!=null&&sig[i]!=null?v-sig[i]:null)}}
export function vwap(c){let pv=0,v=0;return c.map(x=>{const p=(x.high+x.low+x.close)/3;pv+=p*x.volume;v+=x.volume;return v?pv/v:null})}
export function dailyVwap(c){let d=null,pv=0,v=0;return c.map(x=>{const k=Math.floor(x.openTime/86400000);if(k!==d){d=k;pv=0;v=0}const p=(x.high+x.low+x.close)/3;pv+=p*x.volume;v+=x.volume;return v?pv/v:null})}
export function rvol(a,n=20){const o=Array(a.length).fill(null);for(let i=n-1;i<a.length;i++){const b=mean(a.slice(i-n+1,i+1));o[i]=b?a[i]/b:null}return o}
export function adx(c,n=14){const tr=trueRange(c),pdm=Array(c.length).fill(0),mdm=Array(c.length).fill(0);for(let i=1;i<c.length;i++){const u=c[i].high-c[i-1].high,d=c[i-1].low-c[i].low;pdm[i]=u>d&&u>0?u:0;mdm[i]=d>u&&d>0?d:0}const A=rma(tr,n),P=rma(pdm,n),M=rma(mdm,n),dx=Array(c.length).fill(null);for(let i=0;i<c.length;i++)if(A[i]!=null){const p=100*P[i]/A[i],m=100*M[i]/A[i];dx[i]=p+m?100*Math.abs(p-m)/(p+m):0}const vals=dx.filter(num),ad=rma(vals,n),o=Array(c.length).fill(null);let j=0;for(let i=0;i<dx.length;i++)if(dx[i]!=null)o[i]=ad[j++];return o}
export const bodyFrac=c=>{const r=c.high-c.low;return r?Math.abs(c.close-c.open)/r:0};
export const upperWickFrac=c=>{const r=c.high-c.low;return r?(c.high-Math.max(c.open,c.close))/r:0};
export const lowerWickFrac=c=>{const r=c.high-c.low;return r?(Math.min(c.open,c.close)-c.low)/r:0};

export function validateCandle(c){const ok=c&&[c.openTime,c.closeTime,c.open,c.high,c.low,c.close,c.volume].every(num)&&c.openTime<c.closeTime&&c.high>=Math.max(c.open,c.close)&&c.low<=Math.min(c.open,c.close)&&c.high>=c.low&&c.volume>=0;return{valid:ok,issues:ok?[]:['INVALID_CANDLE']}}
export function timeframeMs(tf){return({'5m':300000,'15m':900000,'1h':3600000,'4h':14400000,'1d':86400000}[tf]??0)}
export function validateSeries(c,tf){const issues=[];for(let i=0;i<c.length;i++){if(!validateCandle(c[i]).valid)issues.push(`${tf}:INVALID_${i}`);if(i){const d=c[i].openTime-c[i-1].openTime;if(d<=0)issues.push(`${tf}:DUPLICATE_OR_ORDER_${i}`);const step=timeframeMs(tf);if(step&&d!==step)issues.push(`${tf}:GAP_${i}`)}}return{valid:issues.length===0,issues}}
export function rejectFutureData(c,t){return c.some(x=>x.openTime>t||x.closeTime>t+2592000000)}
export function lastClosedIndex(c){for(let i=c.length-1;i>=0;i--)if(c[i]?.closed===true)return i;return -1}
export function dataQuality({seriesValid=true,staleMs=0,future=false,integrityIssues=0}){if(future)return 0;let q=100;if(!seriesValid)q-=40;q-=Math.min(30,integrityIssues*5);if(staleMs>120000)q-=20;else if(staleMs>60000)q-=10;return clamp(q)}
export function depthWithinBand(book,mid,pct=.005){if(!book?.bids?.length||!book?.asks?.length||!num(mid)||mid<=0)return null;const lo=mid*(1-pct),hi=mid*(1+pct);let b=0,a=0;for(const [p,q] of book.bids)if(num(p)&&num(q)&&p>=lo)b+=p*q;for(const [p,q] of book.asks)if(num(p)&&num(q)&&p<=hi)a+=p*q;return{bidDepth:b,askDepth:a,totalDepth:a+b}}
export function spreadBps(bid,ask){if(!num(bid)||!num(ask)||bid<=0||ask<bid)return null;return(ask-bid)/((ask+bid)/2)*10000}
export function obi(d){return d?.totalDepth>0?(d.bidDepth-d.askDepth)/d.totalDepth:null}
export function liquidityQuality({spread,totalDepth,quoteVolume24h,tradeCount24h,maxSpreadBps=20,minTrades24h=100,minQuoteVolume24h=null}){let s=0,n=0;if(num(spread)){n++;s+=clamp(100*(1-spread/maxSpreadBps))}if(num(totalDepth)){n++;s+=totalDepth>100000?100:totalDepth>25000?80:totalDepth>5000?60:30}if(num(quoteVolume24h)){n++;s+=minQuoteVolume24h?clamp(100*quoteVolume24h/minQuoteVolume24h):norm(Math.log10(Math.max(1,quoteVolume24h)),4,8)}if(num(tradeCount24h)){n++;s+=minTrades24h?clamp(100*tradeCount24h/minTrades24h):60}return n?clamp(s/n):0}

export function priorHigh(c,i,n=20){return i>=n?Math.max(...c.slice(i-n,i).map(x=>x.high)):null}
export function priorLow(c,i,n=20){return i>=n?Math.min(...c.slice(i-n,i).map(x=>x.low)):null}
export function structure(c,i){const H=[],L=[];for(let x=2;x<=i-2;x++){let sh=true,sl=true;for(let k=1;k<=2;k++)if(c[x-k].high>=c[x].high||c[x-k].low<=c[x].low){sh=false;sl=false;break}if(sh)for(let k=1;k<=2;k++)if(c[x+k].high>=c[x].high)sh=false;if(sl)for(let k=1;k<=2;k++)if(c[x+k].low<=c[x].low)sl=false;if(sh)H.push({index:x,confirmationIndex:x+2,price:c[x].high});if(sl)L.push({index:x,confirmationIndex:x+2,price:c[x].low})}const h=H.filter(x=>x.confirmationIndex<=i),l=L.filter(x=>x.confirmationIndex<=i),rh=h.at(-1),ph=h.at(-2),rl=l.at(-1),pl=l.at(-2);return{recentHigh:rh,recentLow:rl,highState:rh&&ph?(rh.price>ph.price?'HH':'LH'):null,lowState:rl&&pl?(rl.price>pl.price?'HL':'LL'):null}}

export const trendScore=x=>clamp((x.regime??0)*.30+(x.alignment??0)*.25+(x.strength??0)*.20+(x.relativeStrength??0)*.15+(x.volume??0)*.10);
export const breakoutScore=x=>clamp((x.priceBreak??0)*.25+(x.volume??0)*.25+(x.liquidity??0)*.20+(x.context??0)*.15+(x.retest??0)*.15);
export const meanReversionScore=x=>clamp((x.location??0)*.30+(x.trendFilter??0)*.25+(x.reversal??0)*.20+(x.volatility??0)*.15+(x.liquidity??0)*.10);
const reject=(strategy,reason)=>({strategy,direction:'NONE',state:'REJECTED',score:{},reasonCodes:[reason]});

export function evaluateMTFTrend({series4h,series1h,series15m,relativeStrength=null,config=CONFIG}){const i4=lastClosedIndex(series4h),i1=lastClosedIndex(series1h),i15=lastClosedIndex(series15m);if(i4<0||i1<0||i15<0)return reject('MTF_TREND','INSUFFICIENT_CLOSED_DATA');const c4=series4h.slice(0,i4+1),c1=series1h.slice(0,i1+1),c15=series15m.slice(0,i15+1),e50=ema(c4.map(x=>x.close),50),e200=ema(c4.map(x=>x.close),200),ad=adx(c4,14),e20=ema(c1.map(x=>x.close),20),e501=ema(c1.map(x=>x.close),50),a15=atr(c15,14),rv=rvol(c15.map(x=>x.volume),20),s=structure(c15,i15),x=c15.at(-1),atr15=a15.at(-1),bull=c4.at(-1).close>e200[i4]&&e50[i4]>e200[i4],bear=c4.at(-1).close<e200[i4]&&e50[i4]<e200[i4],ab=c1.at(-1).close>e501[i1]&&e20[i1]>=e501[i1],aBear=c1.at(-1).close<e501[i1]&&e20[i1]<=e501[i1],pull=atr15&&e20[i1]!=null?Math.abs(x.close-e20[i1])/atr15:Infinity,vol=rv[i15]!=null?norm(rv[i15],.7,1.5):null,strength=ad[i4]!=null?norm(ad[i4],20,40):null,tb=s.highState==='HH'||s.lowState==='HL'||(s.recentHigh&&x.close>s.recentHigh.price+(atr15??0)*.1),td=s.highState==='LH'||s.lowState==='LL'||(s.recentLow&&x.close<s.recentLow.price-(atr15??0)*.1);if(bull&&ab&&pull<=1.5&&tb){const entry=x.close,sl=Math.min(entry-(atr15??0)*1.5,(s.recentLow?.price??entry)-(atr15??0)*.1),r=entry-sl;return{strategy:'MTF_TREND',direction:'LONG',state:'CANDIDATE',score:{trendScore:trendScore({regime:100,alignment:100,strength,relativeStrength,volume:vol})},entry,stopLoss:sl,levels:{tp1:entry+r,tp2:entry+1.5*r,tp3:entry+2*r},evidence:{regime:100,alignment:100,strength,relativeStrength,volume:vol},reasonCodes:['4H_BULL_REGIME','1H_ALIGNED','PULLBACK_OK','STRUCTURE_OR_TRIGGER_OK']}}if(bear&&aBear&&pull<=1.5&&td)return{strategy:'MTF_TREND',direction:'BEARISH',state:'CANDIDATE',score:{trendScore:trendScore({regime:100,alignment:100,strength,relativeStrength:relativeStrength==null?null:100-relativeStrength,volume:vol})},evidence:{regime:100,alignment:100,strength,relativeStrength:relativeStrength==null?null:100-relativeStrength,volume:vol},reasonCodes:['4H_BEAR_REGIME','1H_ALIGNED']};return reject('MTF_TREND','TREND_CONFLUENCE_NOT_MET')}

export function evaluateBreakout({series4h,series1h,series15m,book=null,config=CONFIG}){const i4=lastClosedIndex(series4h),i1=lastClosedIndex(series1h),i15=lastClosedIndex(series15m);if(i4<0||i1<0||i15<0)return reject('CONFIRMED_BREAKOUT','INSUFFICIENT_CLOSED_DATA');const c15=series15m.slice(0,i15+1),c4=series4h.slice(0,i4+1),x=c15.at(-1),a=atr(c15,14).at(-1)??0,rv=rvol(c15.map(c=>c.volume),20).at(-1)??0,res=priorHigh(c15,i15,20),sup=priorLow(c15,i15,20),va=c15.length>=20?mean(c15.slice(-5).map(c=>c.volume))/mean(c15.slice(-20).map(c=>c.volume)):null,ctx=(ema(c4.map(c=>c.close),200)[i4]??0)<c4.at(-1).close,sp=book?.spreadBps??null,li=book?.liquidityQuality??0,ob=book?.obi??null,body=bodyFrac(x),fakeUp=res!=null&&x.high>res&&x.close<res,fakeDn=sup!=null&&x.low<sup&&x.close>sup,common=(rv>=1.5&&(va==null||va>=1.15)&&li>=60&&(sp==null||sp<=20)&&body>=.35);if(res!=null&&x.close>res+a*.1&&common&&!fakeUp&&upperWickFrac(x)<.6&&(ob==null||ob>=.1)){const entry=x.close,sl=res-Math.max(a*.15,a*.1),r=entry-sl;return{strategy:'CONFIRMED_BREAKOUT',direction:'LONG',state:'CONFIRMED',score:{breakoutScore:breakoutScore({priceBreak:100,volume:norm(rv,.8,2),liquidity:li,context:ctx?80:40,retest:0})},entry,stopLoss:sl,levels:{tp1:entry+r,tp2:entry+2*r,tp3:entry+3*r},evidence:{priceBreak:100,volume:norm(rv,.8,2),liquidity:li,context:ctx?80:40,retest:0},reasonCodes:['CLOSE_ABOVE_RANGE','RVOL_OK','LIQUIDITY_OK','NO_FAKEOUT']}}if(sup!=null&&x.close<sup-a*.1&&common&&!fakeDn&&lowerWickFrac(x)<.6&&(ob==null||ob<=-.1))return{strategy:'CONFIRMED_BREAKOUT',direction:'BEARISH',state:'CONFIRMED',score:{breakoutScore:breakoutScore({priceBreak:100,volume:norm(rv,.8,2),liquidity:li,context:ctx?20:80,retest:0})},entry:x.close,stopLoss:sup+Math.max(a*.15,a*.1),levels:{tp1:x.close-a,tp2:x.close-2*a,tp3:x.close-3*a},evidence:{priceBreak:100,volume:norm(rv,.8,2),liquidity:li,context:ctx?20:80,retest:0},reasonCodes:['CLOSE_BELOW_RANGE','RVOL_OK','LIQUIDITY_OK','NO_FAKEOUT']};if(fakeUp||fakeDn)return reject('CONFIRMED_BREAKOUT','FALSE_BREAKOUT');return reject('CONFIRMED_BREAKOUT','BREAKOUT_CONFIRMATION_NOT_MET')}

export function evaluateMeanReversion({series4h,series1h,series15m,liquidityQuality=0,config=CONFIG}){const i4=lastClosedIndex(series4h),i1=lastClosedIndex(series1h),i15=lastClosedIndex(series15m);if(i4<0||i1<0||i15<0)return reject('MEAN_REVERSION','INSUFFICIENT_CLOSED_DATA');const c4=series4h.slice(0,i4+1),c1=series1h.slice(0,i1+1),c15=series15m.slice(0,i15+1),x=c15.at(-1),e=ema(c4.map(c=>c.close),200),ad=adx(c4,14),rr=rsi(c1.map(c=>c.close),14),bb=bollinger(c1.map(c=>c.close),20,2),a1=atr(c1,14),rv=rvol(c15.map(c=>c.volume),20),vw=dailyVwap(c15),s=structure(c15,i15),strongBear=c4.at(-1).close<e[i4]&&(ad[i4]??0)>=30,strongBull=c4.at(-1).close>e[i4]&&(ad[i4]??0)>=30,over=rr[i1]!=null&&rr[i1]<=30,overb=rr[i1]!=null&&rr[i1]>=70,below=bb.lower[i1]!=null&&c1.at(-1).close<=bb.lower[i1],above=bb.upper[i1]!=null&&c1.at(-1).close>=bb.upper[i1],bullRev=x.close>x.open&&lowerWickFrac(x)>=.25,bearRev=x.close<x.open&&upperWickFrac(x)>=.25,panic=(rv[i15]??0)>=3&&bodyFrac(x)>=.65&&x.close<x.open;if(panic)return reject('MEAN_REVERSION','PANIC_SELL_FILTER');if(over&&below&&!strongBear&&bullRev&&liquidityQuality>=60){const a=a1[i1]??0,entry=x.close,sl=Math.min(entry-a*1.5,(s.recentLow?.price??entry)-a*.25),r=entry-sl,v=vw[i15],tp1=bb.middle[i1]!=null&&bb.middle[i1]>entry?bb.middle[i1]:entry+r,tp2=entry+1.5*r,tp3=v!=null&&v>entry?v:entry+2*r;return{strategy:'MEAN_REVERSION',direction:'LONG',state:'CANDIDATE',score:{meanReversionScore:meanReversionScore({location:Math.min(100,(30-rr[i1])*10),trendFilter:strongBull?90:70,reversal:75,volatility:rv[i15]!=null?70:40,liquidity:liquidityQuality})},entry,stopLoss:sl,levels:{tp1,tp2,tp3},evidence:{trendFilter:strongBull?90:70,reversal:75,volatility:rv[i15]!=null?70:40,liquidity:liquidityQuality},reasonCodes:['OVERSOLD','LOWER_BAND','REGIME_FILTER_OK','REVERSAL_OK']}}if(overb&&above&&!strongBull&&bearRev&&liquidityQuality>=60)return{strategy:'MEAN_REVERSION',direction:'BEARISH',state:'CANDIDATE',score:{meanReversionScore:meanReversionScore({location:Math.min(100,(rr[i1]-70)*10),trendFilter:strongBear?90:70,reversal:75,volatility:70,liquidity:liquidityQuality})},evidence:{trendFilter:strongBear?90:70,reversal:75,volatility:70,liquidity:liquidityQuality},reasonCodes:['OVERBOUGHT','UPPER_BAND','BEARISH_REVERSAL']};return reject('MEAN_REVERSION','MEAN_REVERSION_FILTER_NOT_MET')}

export function roundTripNetRR({entry,stop,target,feeRate,slippageBps}){if(![entry,stop,target,feeRate,slippageBps].every(num)||entry<=stop)return'UNKNOWN';const s=slippageBps/10000,fillIn=entry*(1+s),exit=target*(1-s),risk=fillIn-stop,net=(exit-fillIn)*(1-feeRate)-fillIn*feeRate;return risk>0?net/risk:'UNKNOWN'}
export function riskFilter({candleClosed,dataQuality,liquidityQuality,netRR='UNKNOWN',minRR=1.5,future=false,invalid=false}){const reasons=[];if(!candleClosed)reasons.push('INCOMPLETE_CANDLE');if(future)reasons.push('FUTURE_DATA');if(invalid)reasons.push('INVALID_DATA');if(dataQuality<70)reasons.push('LOW_DATA_QUALITY');if(liquidityQuality<60)reasons.push('LOW_LIQUIDITY');if(netRR==='UNKNOWN')reasons.push('UNKNOWN_COST_MODEL');else if(netRR<minRR)reasons.push('LOW_NET_RR');return{value:reasons.length?'FAIL':'PASS',reasons}}
export function makeSignal({symbol,strategy,direction,signalType,candle,price={},scores={},dataQuality=0,liquidityQuality=0,risk={value:'FAIL',reasons:['UNKNOWN']},evidence={},costs={},source='UNKNOWN',reasonCodes=[]}){return{signal_id:globalThis.crypto?.randomUUID?.()??`sig-${Date.now()}`,symbol,market:'SPOT',strategy,direction,signal_type:signalType??'ENTRY_CANDIDATE',decision_timestamp:Date.now(),candle:{timeframe:candle?.timeframe??'UNKNOWN',open_time:candle?.openTime??null,close_time:candle?.closeTime??null,closed:candle?.closed===true},price:{reference:price.reference??null,entry:price.entry??null,stop_loss:price.stop_loss??null,tp1:price.tp1??null,tp2:price.tp2??null,tp3:price.tp3??null},scores:{trend_score:scores.trendScore??0,breakout_score:scores.breakoutScore??0,mean_reversion_score:scores.meanReversionScore??0,data_quality:dataQuality,liquidity_quality:liquidityQuality,confidence_score:'UNKNOWN',confidence_state:'UNCALIBRATED'},risk_filter:risk.value,risk_reasons:risk.reasons,evidence,reason_codes:reasonCodes,cost_model:{fee_rate:costs.feeRate??'UNKNOWN',slippage_bps:costs.slippageBps??'UNKNOWN',net_rr:costs.netRR??'UNKNOWN'},data_status:{source,stale:Boolean(costs.stale),gaps:Boolean(costs.gaps),future_data_detected:Boolean(costs.futureDataDetected)},dedup:{state_key:[symbol,strategy,direction,candle?.closeTime??'UNKNOWN'].join('|'),cooldown_until:null},paper_trading:true,paper_trade:{enabled:true,real_order_execution:false}}}
export function shouldEmitSignal(prev,current,{now=Date.now(),cooldownMs=CONFIG.dedup.cooldownMs}={}){if(!current?.dedup?.state_key)return false;if(prev?.dedup?.state_key===current.dedup.state_key)return false;if(prev&&prev.strategy===current.strategy&&prev.direction===current.direction&&now-prev.decision_timestamp<cooldownMs)return false;return true}

const BASES=['https://api.binance.com','https://api-gcp.binance.com','https://api1.binance.com','https://api2.binance.com','https://api3.binance.com','https://api4.binance.com','https://data-api.binance.vision'];
async function getJson(url,fetchImpl=globalThis.fetch,timeoutMs=9000){if(typeof fetchImpl!=='function')throw Error('FETCH_UNAVAILABLE');const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),timeoutMs);try{const r=await fetchImpl(url,{signal:ac.signal,headers:{Accept:'application/json'}});if(!r.ok)throw Error(`HTTP_${r.status}`);return await r.json()}catch(e){if(e.name==='AbortError')throw Error('TIMEOUT');throw e}finally{clearTimeout(tm)}}
export function normalizeKline(x,source='UNKNOWN'){if(!Array.isArray(x)||x.length<11)throw Error('INVALID_KLINE');return{openTime:+x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5],closeTime:+x[6],quoteVolume:+x[7],tradeCount:+x[8],takerBuyBaseVolume:+x[9],takerBuyQuoteVolume:+x[10],closed:false,source}}
export function closedKline(c,now=Date.now()){return{...c,closed:c.closeTime<now}}
export class BinancePublicData{constructor({baseUrls=BASES,fetchImpl=globalThis.fetch,timeoutMs=9000}={}){this.baseUrls=[...baseUrls];this.fetchImpl=fetchImpl;this.timeoutMs=timeoutMs}async request(path,query={}){const q=new URLSearchParams(query),errors=[];for(const b of this.baseUrls)try{return{data:await getJson(`${b}${path}?${q}`,this.fetchImpl,this.timeoutMs),source:b}}catch(e){errors.push(`${b}:${e.message}`)}throw Error('ALL_DATA_SOURCES_FAILED:'+errors.join('|'))}async klines(symbol,interval,limit=250){const r=await this.request('/api/v3/klines',{symbol,interval,limit:String(limit)}),now=Date.now();return{candles:r.data.map(x=>closedKline(normalizeKline(x,'BINANCE_PUBLIC_REST'),now)),source:r.source}}async depth(symbol,limit=100){return this.request('/api/v3/depth',{symbol,limit:String(limit)})}async ticker24h(symbol){return this.request('/api/v3/ticker/24hr',{symbol})}async exchangeInfo(symbol){return this.request('/api/v3/exchangeInfo',symbol?{symbol}:{})}}
export const publicMarketOnlyPolicy=Object.freeze({authenticationRequired:false,allowsTradeEndpoints:false,allowsWithdrawals:false,allowsUserData:false,mode:'READ_ONLY'});

export function evaluateSymbolSnapshot({symbol,series4h,series1h,series15m,bookRaw=null,ticker24hRaw=null,source='UNKNOWN',now=Date.now()},{config=CONFIG}={}){const v4=validateSeries(series4h,'4h'),v1=validateSeries(series1h,'1h'),v15=validateSeries(series15m,'15m'),invalid=!v4.valid||!v1.valid||!v15.valid,future=rejectFutureData([...series4h,...series1h,...series15m],now),i15=lastClosedIndex(series15m),lc=i15>=0?series15m[i15]:null,stale=lc?Math.max(0,now-lc.closeTime):Infinity,dq=dataQuality({seriesValid:!invalid,staleMs:stale,future,integrityIssues:v4.issues.length+v1.issues.length+v15.issues.length});let book=null,lq=0;if(bookRaw?.bids?.length&&bookRaw?.asks?.length){const bid=+bookRaw.bids[0][0],ask=+bookRaw.asks[0][0],d=depthWithinBand(bookRaw,(bid+ask)/2,config.liquidity.depthBandPct),sp=spreadBps(bid,ask),o=obi(d),q=Number(ticker24hRaw?.quoteVolume),t=Number(ticker24hRaw?.count);lq=liquidityQuality({spread:sp,totalDepth:d?.totalDepth??0,quoteVolume24h:num(q)?q:null,tradeCount24h:num(t)?t:null,maxSpreadBps:20,minTrades24h:100});book={bid,ask,spreadBps:sp,obi:o,liquidityQuality:lq}}const trend=evaluateMTFTrend({series4h,series1h,series15m,config}),breakout=evaluateBreakout({series4h,series1h,series15m,book,config}),meanReversion=evaluateMeanReversion({series4h,series1h,series15m,liquidityQuality:lq,config}),cand=[trend,breakout,meanReversion].filter(x=>x.state!=='REJECTED'),chosen=cand.sort((a,b)=>(Object.values(b.score).find(num)??0)-(Object.values(a.score).find(num)??0))[0]??{strategy:'NO_SIGNAL',direction:'NONE',state:'REJECTED',score:{},reasonCodes:['NO_STRATEGY_TRIGGERED']},rr=num(config.costs.feeRate)&&num(config.costs.slippageBps)&&num(chosen.entry)&&num(chosen.stopLoss)&&num(chosen.levels?.tp2)?roundTripNetRR({entry:chosen.entry,stop:chosen.stopLoss,target:chosen.levels.tp2,feeRate:config.costs.feeRate,slippageBps:config.costs.slippageBps}):'UNKNOWN',risk=riskFilter({candleClosed:lc?.closed===true,dataQuality:dq,liquidityQuality:lq,netRR:rr,minRR:config.trend.minNetRR,future,invalid});return{signal:makeSignal({symbol,strategy:chosen.strategy,direction:chosen.direction,signalType:chosen.state==='CONFIRMED'?'CONFIRMED':'ENTRY_CANDIDATE',candle:{timeframe:'15m',...(lc||{})},price:{reference:lc?.close??null,entry:chosen.entry??null,stop_loss:chosen.stopLoss??null,tp1:chosen.levels?.tp1??null,tp2:chosen.levels?.tp2??null,tp3:chosen.levels?.tp3??null},scores:chosen.score,dataQuality:dq,liquidityQuality:lq,risk,evidence:chosen.evidence??{},costs:{feeRate:config.costs.feeRate,slippageBps:config.costs.slippageBps,netRR:rr,stale:stale>120000,gaps:invalid,futureDataDetected:future},source,reasonCodes:chosen.reasonCodes??[]}),strategies:{trend,breakout,meanReversion},diagnostics:{dataQuality:dq,liquidityQuality:lq,book,source,latestClosed15m:lc?.closeTime??null,futureDataDetected:future}}}
